apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-container
        image: aniljeenapati/demo:latest3
        ports:
        - containerPort: 8080  # Change this to the port your application listens on
        env:
        - name: ENV_VAR_NAME  # Add environment variables here if needed
          value: "value"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  type: LoadBalancer  # Expose the service externally
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 80       # Port for external access
    targetPort: 8080  # Port your application listens on in the container
