apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: aniljeenapati/demo:latest1
        ports:
        - containerPort: 80

