project_id        = "your-gcp-project-id"
region            = "us-central1"
cluster_name      = "my-gke-cluster"
machine_type      = "e2-medium"
initial_node_count = 3
node_locations    = ["us-central1-a", "us-central1-b", "us-central1-c"]
node_count        = 3
min_node_count    = 1
max_node_count    = 5
